kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: PLeaQ7SA+oaO4ZnqXbYV3Y25ErrXNmpCcPGUw37CzVk=
      - identity: {}
