apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: dd-webhook
  name: dd-webhook
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-webhook
  template:
    metadata:
      labels:
        app: dd-webhook
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: api.huisebug.com
      containers:
      - image: timonwong/prometheus-webhook-dingtalk
        args: 
        #如果要设置不同的钉钉机器人webhook就再增加一行
        - --ding.profile="ops_dingding=https://oapi.dingtalk.com/robot/send?access_token=钉钉机器人webhook1"
        #- --ding.profile="ops_dingding=https://oapi.dingtalk.com/robot/send?access_token=钉钉机器人webhook2"
        name: dd-webhook
        ports:
        - containerPort: 8060
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
            


