global:
  resolve_timeout: 1h
route:
  receiver: webhook
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 3h
  group_by: [alertname]
  routes:
  - receiver: webhook
    group_wait: 30s
    match:
      team: node
receivers:
- name: webhook
  webhook_configs:
  - url: http://192.168.137.13:8060/dingtalk/ops_dingding/send
    send_resolved: true
