apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogMWgKcm91dGU6CiAgcmVjZWl2ZXI6IHdlYmhvb2sKICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogMzBzCiAgcmVwZWF0X2ludGVydmFsOiAzaAogIGdyb3VwX2J5OiBbYWxlcnRuYW1lXQogIHJvdXRlczoKICAtIHJlY2VpdmVyOiB3ZWJob29rCiAgICBncm91cF93YWl0OiAzMHMKICAgIG1hdGNoOgogICAgICB0ZWFtOiBub2RlCnJlY2VpdmVyczoKLSBuYW1lOiB3ZWJob29rCiAgd2ViaG9va19jb25maWdzOgogIC0gdXJsOiBodHRwOi8vMTkyLjE2OC4xMzcuMTM6ODA2MC9kaW5ndGFsay9vcHNfZGluZ2Rpbmcvc2VuZAogICAgc2VuZF9yZXNvbHZlZDogdHJ1ZQo=
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
