apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: sample-app
  name: sample-app
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    port: web
    scheme: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: sample-app

