apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: mysql-rc
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: mysql-rc
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 1300Mi
